### ISSUE TITLE
unity 2019 says--->>   The type or namespace name 'PrefabStage' does not exist in the namespace 'UnityEditor.SceneManagement' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by jfkdcman** [DHS5/DFL-2#1]
unity 2019 says--->>   The type or namespace name 'PrefabStage' does not exist in the namespace 'UnityEditor.SceneManagement' (are you missing an assembly reference?)

In this file PrefabSavingUtil

Please tell me how to solve please

**Comment by DHS5** [comment]
I use Unity 2021, maybe the problem comes from your version. If not, I don't know how to help you sorry.
